[tool.bumpversion]
current_version = "5.0.0-alpha.0"
parse = "(?P<major>\\d+)\\.(?P<minor>\\d+)\\.(?P<patch>\\d+)(-(?P<pre>alpha|beta|rc)\\.(?P<prenum>\\d+))?"
serialize = [
    "{major}.{minor}.{patch}-{pre}.{prenum}",
    "{major}.{minor}.{patch}",
]
search = "{current_version}"
replace = "{new_version}"
regex = false
ignore_missing_version = false
tag = true
sign_tags = false
tag_name = "v{new_version}"
tag_message = "Bump version: {current_version} → {new_version}"
allow_dirty = false
commit = true
message = "Bump version: {current_version} → {new_version}"
commit_args = ""

[tool.bumpversion.parts.pre]
optional_value = "release"
values = ["alpha", "beta", "rc", "release"]

[[tool.bumpversion.files]]
filename = "VERSION"

[[tool.bumpversion.files]]
filename = "./rsenv/Cargo.toml"
search = 'version = "{current_version}"'
replace = 'version = "{new_version}"'
